EQUIPMENT_LIST = [
    # Dumbbell variants (extended up to 120lbs) with 'lbs' removed
    "Dumbbells_5",
    "Dumbbells_7.5",
    "Dumbbells_10",
    "Dumbbells_12.5",
    "Dumbbells_15",
    "Dumbbells_17.5",
    "Dumbbells_20",
    "Dumbbells_25",
    "Dumbbells_30",
    "Dumbbells_35",
    "Dumbbells_40",
    "Dumbbells_45",
    "Dumbbells_50",
    "Dumbbells_55",
    "Dumbbells_60",
    "Dumbbells_65",
    "Dumbbells_70",
    "Dumbbells_75",
    "Dumbbells_80",
    "Dumbbells_85",
    "Dumbbells_90",
    "Dumbbells_95",
    "Dumbbells_100",
    "Dumbbells_105",
    "Dumbbells_110",
    "Dumbbells_115",
    "Dumbbells_120",

    # Kettlebell variants (extended up to 120lbs) with 'lbs' removed
    "Kettlebells_5",
    "Kettlebells_10",
    "Kettlebells_15",
    "Kettlebells_20",
    "Kettlebells_25",
    "Kettlebells_30",
    "Kettlebells_35",
    "Kettlebells_40",
    "Kettlebells_45",
    "Kettlebells_50",
    "Kettlebells_55",
    "Kettlebells_60",
    "Kettlebells_65",
    "Kettlebells_70",
    "Kettlebells_75",
    "Kettlebells_80",
    "Kettlebells_85",
    "Kettlebells_90",
    "Kettlebells_95",
    "Kettlebells_100",
    "Kettlebells_105",
    "Kettlebells_110",
    "Kettlebells_115",
    "Kettlebells_120",

    "Fixed_weight_bar_10",
    "Fixed_weight_bar_15",
    "Fixed_weight_bar_20",
    "Fixed_weight_bar_25",
    "Fixed_weight_bar_30",
    "Fixed_weight_bar_35",
    "Fixed_weight_bar_40",
    "Fixed_weight_bar_45",
    "Fixed_weight_bar_50",
    "Fixed_weight_bar_55",
    "Fixed_weight_bar_60",
    "Fixed_weight_bar_65",
    "Fixed_weight_bar_70",
    "Fixed_weight_bar_75",
    "Fixed_weight_bar_80",
    "Fixed_weight_bar_85",
    "Fixed_weight_bar_90",
    "Fixed_weight_bar_95",
    "Fixed_weight_bar_100",
    "Fixed_weight_bar_105",
    "Fixed_weight_bar_110",
    "Fixed_weight_bar_115",
    "Fixed_weight_bar_120",
    "Fixed_weight_bar_125",
    "Fixed_weight_bar_130",
    "Fixed_weight_bar_135",
    "Fixed_weight_bar_140",
    "Fixed_weight_bar_145",
    "Fixed_weight_bar_150",
    "Fixed_weight_bar_155",
    "Fixed_weight_bar_160",

    "Mini_loop_band_ELight",
    "Mini_loop_band_Light",
    "Mini_loop_band_Medium",
    "Mini_loop_band_Heavy",
    "Mini_loop_band_XHeavy",

    "Regular_loop_band_ELight",
    "Regular_loop_band_Light",
    "Regular_loop_band_Medium",
    "Regular_loop_band_Heavy",
    "Regular_loop_band_XHeavy",

    "Handle_band_ELight",
    "Handle_band_Light",
    "Handle_band_Medium",
    "Handle_band_Heavy",
    "Handle_band_XHeavy",

    # Remaining equipment (unchanged)
    "1 Ankle strap",
    "2 Ankle strap",
    "1 Single grip handle",
    "2 Single grip handle",
    "45-degree leg press machine",
    "Adjustable pulley",
    "Assisted dip machine",
    "Assisted pull up machine",
    "Back extension station",
    "Hack squat machine",
    "Bench",
    "Chest supported T-bar",
    "Curl bar",
    "Decline bench",
    "Dip machine",
    "EZ curl bar",
    "Fixed weight bar",
    "Flat chest press machine",
    "Functional trainer cable machine",
    "Hex trap bar",
    "High pulley",
    "Horizontal leg press machine",
    "Incline bench",
    "Incline chest press machine",
    "Landmine base",
    "Lat pulldown cable machine",
    "Low pulley",
    "Lying down hamstring curl machine",
    # "Mini loop band",
    "None",
    "Olympic barbell",
    "PVC pipe",
    "Parallel bars",
    "Pec deck machine",
    "Plate loaded lat pull down machine",
    "Plated row machine",
    "Platform",
    "Plyometric box",
    "Power tower",
    "Preacher bench",
    "Pull up bar",
    "Pull up station",
    "Pullover machine",
    "Quad extension machine",
    "Rope",
    "Resistance band bar",
    "Seated abduction machine",
    "Seated adduction machine",
    "Seated cable pec fly machine",
    "Seated cable row machine",
    "Seated chest press machine",
    "Seated hamstring curl machine",
    "Seated lateral raise machine",
    "Seated overhead tricep extension machine",
    "Seated plated calf machine",
    "Seated shoulder press machine",
    "Seated tricep extension machine",
    "Smith machine",
    "Stability ball",
    "Standing lateral raise machine",
    "Standing plated calf machine",
    "Straight bar",
    "TRX",
    "Triceps V-bar",
    "Weight plates"
]
